#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:
        en: ''
        ru: '/ru'
